tg_cpphost: socket: Convert to dynamic array initialization
- Now we get 2 errors at least if those doesn't match

c_cpp_telegrambot/src/socket/TgBotCommandMap.cpp:9:12: error: redefinition of 'kTgBotCommandArgsCount' with a different type: 'const array<[...], sizeof...(V) aka 2>' vs 'const array<[...], 3 aka 3>'
const auto kTgBotCommandArgsCount = make_array<ConstArrayElem<TgBotCommand, int>, CMD_MAX - 1> (
           ^
c_cpp_telegrambot/src/socket/TgBotSocket.h:31:5: error: static assertion failed due to requirement 'sizeof...(V) == 3': Must match declared size
    static_assert(sizeof...(V) == N, "Must match declared size");
    ^             ~~~~~~~~~~~~~~~~~
c_cpp_telegrambot/src/socket/TgBotSocket.h:31:32: note: expression evaluates to '2 == 3'
    static_assert(sizeof...(V) == N, "Must match declared size");
                  ~~~~~~~~~~~~~^~~~
2 errors generated.